version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: country_cache
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 3
  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=country_cache
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - APP_HOST=0.0.0.0
      - APP_PORT=8000
      - REFRESH_TIMEOUT_SECONDS=20
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
volumes:
  postgres_data:
